version: 2.1

jobs:

  runner:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

    environment:
      GH_REPO: $GHA_Meta

    steps:
      - checkout
      - run: ./runner.sh
          -s repo
          -n "circle-${CIRCLE_WORKFLOW_ID}"
          -d 
