version: 2.1

parameters:
  GH_REPO:
    type: string
    default: ""

jobs:

  runner:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

    steps:
      - checkout
      - run: |
          echo "GH_REPO: << pipeline.parameters.GH_REPO >>"
          ./runner.sh \
            -s "<< pipeline.parameters.GH_REPO >>" \
            -n "circle-${CIRCLE_WORKFLOW_ID}" \
            -d 

workflows:
  runner:
    jobs:
      - runner
