version: 2.1

parameters:
  GH_REPO:
    type: string
    default: ""

jobs:

  runner:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

    steps:
      - checkout
      - run: ./runner.sh
          -s "$GH_REPO"
          -n "circle-${CIRCLE_WORKFLOW_ID}"
          -d 

workflows:
  runner:
    jobs:
      - runner
